---
# Install and configure MicroK8s with required addons
- name: Check if MicroK8s is installed
  ansible.builtin.command: microk8s status --wait-ready
  register: microk8s_check
  ignore_errors: true

- name: Install MicroK8s
  community.general.snap:
    name: microk8s
    classic: yes
    channel: 1.30/stable
    state: present
  become: true
  when: microk8s_check.rc != 0

- name: Add user to microk8s group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: microk8s
    append: yes
  become: true

- name: Reset ssh connection to allow user changes to affect 'current login user'
  ansible.builtin.meta: reset_connection

- name: Change ownership of ~/.kube
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.kube"
    owner: "{{ ansible_user_id }}"
    recurse: yes
  become: true
  ignore_errors: true

- name: Enable MicroK8s addons
  ansible.builtin.command: "microk8s enable dns helm3 ingress metrics-server storage registry --size 20Gi"
  changed_when: false

- name: Wait for MicroK8s to be ready
  ansible.builtin.command: microk8s status --wait-ready
  changed_when: false

- name: Wait for registry service to be ready
  ansible.builtin.uri:
    url: http://localhost:32000/v2/
    method: GET
    status_code: 200
  register: registry_check
  until: registry_check.status == 200
  retries: 30
  delay: 10
  ignore_errors: false

- name: Test MicroK8s access
  ansible.builtin.command: microk8s status
  register: microk8s_test
  changed_when: false
  failed_when: false

- name: Print MicroK8s install message
  ansible.builtin.debug:
    msg: "MicroK8s setup complete. MicroK8s access: {{ 'Working' if microk8s_test.rc == 0 else 'May require logout/login or newgrp microk8s' }}"
