- name: Get docker group GID
  getent:
    database: group
    key: docker
  register: docker_group

- name: Build custom Jenkins image
  community.docker.docker_image:
    name: jenkins-devsecops:latest
    build:
      path: "{{ playbook_dir }}/../../jenkins"
      args:
        DOCKER_GID: "{{ docker_group.ansible_facts.getent_group.docker[1] | default('999') }}"
    source: build
    state: present

- name: Tag Jenkins image for local registry
  community.docker.docker_tag:
    src: jenkins-devsecops:latest
    target: localhost:32000/jenkins-devsecops:latest

- name: Push Jenkins image to local registry
  command: docker push localhost:32000/jenkins-devsecops:latest
