---
# Deploy Jenkins, SonarQube, and PostgreSQL using Helm and K8s manifests
- name: Create namespaces for Jenkins and SonarQube
  ansible.builtin.shell: |
    microk8s kubectl apply -f {{ playbook_dir }}/../k8s/namespace.yaml
    microk8s kubectl get ns jenkins || microk8s kubectl create ns jenkins
    microk8s kubectl get ns sonarqube || microk8s kubectl create ns sonarqube
  args:
    executable: /bin/bash

- name: Add Helm repositories
  ansible.builtin.shell: |
    microk8s helm3 repo add jenkins https://charts.jenkins.io
    microk8s helm3 repo add bitnami https://charts.bitnami.com/bitnami
    microk8s helm3 repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
    microk8s helm3 repo update
  args:
    executable: /bin/bash

- name: Deploy Jenkins via Helm
  ansible.builtin.shell: |
    microk8s helm3 status jenkins -n jenkins || microk8s helm3 install jenkins jenkins/jenkins -n jenkins -f {{ playbook_dir }}/../helm/jenkins/values.yaml
  args:
    executable: /bin/bash

- name: Deploy PostgreSQL for SonarQube
  ansible.builtin.shell: |
    microk8s helm3 status postgresql -n sonarqube || microk8s helm3 install postgresql bitnami/postgresql -n sonarqube -f {{ playbook_dir }}/../helm/postgresql/values.yaml
  args:
    executable: /bin/bash

- name: Deploy SonarQube via Helm
  ansible.builtin.shell: |
    microk8s helm3 status sonarqube -n sonarqube || microk8s helm3 install sonarqube sonarqube/sonarqube -n sonarqube -f {{ playbook_dir }}/../helm/sonarqube/values.yaml
  args:
    executable: /bin/bash

- name: Wait for Jenkins StatefulSet
  ansible.builtin.shell: microk8s kubectl rollout status statefulset/jenkins -n jenkins --timeout=5m
  args:
    executable: /bin/bash

- name: Wait for PostgreSQL StatefulSet
  ansible.builtin.shell: microk8s kubectl rollout status statefulset/postgresql -n sonarqube --timeout=5m
  args:
    executable: /bin/bash

- name: Wait for SonarQube StatefulSet
  ansible.builtin.shell: microk8s kubectl rollout status statefulset/sonarqube-sonarqube -n sonarqube --timeout=5m
  args:
    executable: /bin/bash
