apiVersion: v1
kind: Service
metadata:
  name: alloy-webhook-service
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - name: webhook
      port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app.kubernetes.io/name: alloy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alloy-webhook-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /webhook
spec:
  ingressClassName: public
  rules:
    - host: webhook.${EXTERNAL_IP}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alloy-webhook-service
                port:
                  number: 9999
