---
all:
  children:
    devsecops:
      hosts:
        devsecops-server:
          ansible_host: 10.0.0.10  # Replace with your target server IP
          ansible_user: ubuntu      # Replace with your SSH user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Path to your SSH key
          
    # Example for multiple servers
    # devsecops-cluster:
    #   hosts:
    #     devsecops-master:
    #       ansible_host: 10.0.0.10
    #       ansible_user: ubuntu
    #       node_role: master
    #     devsecops-worker1:
    #       ansible_host: 10.0.0.11
    #       ansible_user: ubuntu
    #       node_role: worker
    #     devsecops-worker2:
    #       ansible_host: 10.0.0.12
    #       ansible_user: ubuntu
    #       node_role: worker

    # Local development (uncomment to use localhost)
    # localhost:
    #   hosts:
    #     127.0.0.1:
    #       ansible_connection: local
    #       ansible_python_interpreter: /usr/bin/python3
