---
- name: Create SIEM directory
  file:
    path: /opt/siem
    state: directory
    mode: '0755'

- name: Copy SIEM Alloy configuration
  copy:
    src: "{{ playbook_dir }}/../siem/alloy-siem-config.alloy"
    dest: /opt/siem/alloy-siem-config.alloy
    mode: '0644'

- name: Create webhook service for Git monitoring
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: alloy-webhook-service
        namespace: monitoring
      spec:
        type: LoadBalancer
        ports:
          - name: webhook
            port: 9999
            targetPort: 9999
            protocol: TCP
        selector:
          app.kubernetes.io/name: alloy

- name: Create webhook ingress for external access
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: alloy-webhook-ingress
        namespace: monitoring
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /webhook
      spec:
        ingressClassName: public
        rules:
          - host: "webhook.{{ ansible_default_ipv4.address }}.nip.io"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: alloy-webhook-service
                      port:
                        number: 9999

- name: Configure host log directories to be accessible by Alloy
  file:
    path: /var/log
    mode: '0755'
    recurse: yes

- name: Create log rotation configuration for security logs
  copy:
    dest: /etc/logrotate.d/siem-security
    content: |
      /var/log/auth.log
      /var/log/secure
      /var/log/syslog {
          daily
          missingok
          rotate 30
          compress
          delaycompress
          notifempty
          postrotate
              /bin/kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true
          endscript
      }

- name: Ensure rsyslog is running for system logging
  systemd:
    name: rsyslog
    enabled: yes
    state: started

- name: Configure SSH logging for better SIEM integration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LogLevel'
    line: 'LogLevel VERBOSE'
    backup: yes
  notify: restart sshd

- name: Configure audit logging
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^log_file'
    line: 'log_file = /var/log/audit/audit.log'
    backup: yes
  notify: restart auditd

- name: Enable and start auditd service
  systemd:
    name: auditd
    enabled: yes
    state: started
