---
- name: restart auditd
  systemd:
    name: auditd
    state: restarted
  become: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
  become: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  become: yes