persistence:
  enabled: true
  storageClassName: "microk8s-hostpath"
  size: "2Gi"
  accessModes:
    - ReadWriteOnce

# Disable the problematic init container
initChownData:
  enabled: false

# Security context to run as root (for MicroK8s hostpath)
podSecurityContext:
  fsGroup: 0
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false

securityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  allowPrivilegeEscalation: true

adminPassword: "admin123"
ingress:
  enabled: true
  ingressClassName: public
  hosts:
    - grafana.local
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      uid: loki
      isDefault: true
      version: 1
      editable: false
      orgId: 1

# Additional configuration to prevent permission issues
serviceAccount:
  create: true
  
# Ensure proper volume mounts
extraVolumeMounts:
  - name: grafana-storage
    mountPath: /var/lib/grafana
    
# Environment variables for Grafana
env:
  GF_PATHS_DATA: /var/lib/grafana
  GF_PATHS_LOGS: /var/log/grafana
  GF_PATHS_PLUGINS: /var/lib/grafana/plugins
  GF_INSTALL_PLUGINS: ""

podSecurityContext:
  fsGroup: 0
  runAsUser: 0
  runAsGroup: 0
