persistence:
  enabled: true
  storageClassName: "microk8s-hostpath"
  size: "2Gi"
adminPassword: "admin123"
ingress:
  enabled: true
  ingressClassName: public
  hosts:
    - grafana.local
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      uid: loki
      isDefault: true
      version: 1
      editable: false
      orgId: 1
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
    searchNamespace: ALL
    provider:
      allowUiUpdates: true
      disableDelete: false
  datasources:
    enabled: true
    label: grafana_datasource
    searchNamespace: ALL
initChownData:
  enabled: false