persistence:
  enabled: true
  storageClassName: "microk8s-hostpath"
  size: "2Gi"
adminPassword: "admin123"
ingress:
  enabled: true
  ingressClassName: public
  hosts:
    - grafana.local
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      uid: loki
      isDefault: true
      version: 1
      editable: false
      orgId: 1
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    siem-security:
      file: dashboards/siem-security.json
    app-logs:
      file: dashboards/app-logs.json
    security:
      file: dashboards/security.json
initChownData:
  enabled: false