apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-app
  labels:
    app: flask-app
data:
  PORT: "5000"
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: "INFO"
  APP_NAME: "flask-k8s-app"
  APP_VERSION: "1.0.0"
