apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: flask-app
  labels:
    app: flask-app
type: Opaque
data:
  SECRET_KEY: Zmxhc2stc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbg==
  DATABASE_PASSWORD: c2VjdXJlLWRhdGFiYXNlLXBhc3N3b3Jk
  API_TOKEN: YXBpLXRva2VuLWZvci1leHRlcm5hbC1zZXJ2aWNlcw==
