alloy:
  configMap:
    create: true
    content: |
      // System log collection for SIEM
      loki.source.file "auth_logs" {
        targets = [
          {__path__ = "/var/log/auth.log", job = "auth", log_type = "security"},
        ]
        forward_to = [loki.process.auth_logs.receiver]
      }

      loki.source.file "system_logs" {
        targets = [
          {__path__ = "/var/log/syslog", job = "system", log_type = "system"},
          {__path__ = "/var/log/dpkg.log", job = "packages", log_type = "system_changes"},
        ]
        forward_to = [loki.process.system_logs.receiver]
      }

      loki.source.file "audit_logs" {
        targets = [
          {__path__ = "/var/log/audit/audit.log", job = "audit", log_type = "security"},
        ]
        forward_to = [loki.process.audit_logs.receiver]
      }

      loki.source.file "webhook_logs" {
        targets = [
          {__path__ = "/tmp/webhooks/webhook-*.log", job = "webhook", log_type = "code_changes"},
        ]
        forward_to = [loki.process.webhook_logs.receiver]
      }

      // Process authentication logs
      loki.process "auth_logs" {
        stage.regex {
          expression = "(?P<timestamp>\\w+\\s+\\d+\\s+\\d+:\\d+:\\d+)\\s+(?P<hostname>\\S+)\\s+(?P<service>\\w+)(?:\\[(?P<pid>\\d+)\\])?:\\s*(?P<message>.*)"
        }
        
        stage.labels {
          values = {
            hostname = "",
            service = "",
            log_type = "security",
          }
        }

        forward_to = [loki.write.default.receiver]
      }

      // Process system logs
      loki.process "system_logs" {
        stage.regex {
          expression = "(?P<timestamp>\\w+\\s+\\d+\\s+\\d+:\\d+:\\d+)\\s+(?P<hostname>\\S+)\\s+(?P<service>\\w+)(?:\\[(?P<pid>\\d+)\\])?:\\s*(?P<message>.*)"
        }
        
        stage.labels {
          values = {
            hostname = "",
            service = "",
            log_type = "",
          }
        }

        forward_to = [loki.write.default.receiver]
      }

      // Process audit logs
      loki.process "audit_logs" {
        stage.regex {
          expression = "type=(?P<audit_type>\\w+).*"
        }
        
        stage.labels {
          values = {
            audit_type = "",
            log_type = "security",
          }
        }

        forward_to = [loki.write.default.receiver]
      }

      // Process webhook logs
      loki.process "webhook_logs" {
        stage.regex {
          expression = ".*\"(?P<method>\\w+)\\s+(?P<path>/\\w+).*\"\\s+(?P<status>\\d+).*"
        }
        
        stage.labels {
          values = {
            method = "",
            path = "",
            status = "",
            log_type = "code_changes",
          }
        }

        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint {
          url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        }
      }
