apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
  namespace: monitoring
  labels:
    app: webhook-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
      - name: webhook-receiver
        image: localhost:32000/webhook-receiver:latest
        ports:
        - containerPort: 5000
        env:
        - name: LOKI_URL
          value: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver-service
  namespace: monitoring
spec:
  selector:
    app: webhook-receiver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
