# Fail2Ban configuration for SSH protection

[DEFAULT]
ignoreip = 127.0.0.1/8 ::1
bantime = 600
findtime = 600
maxretry = 5
banaction = iptables-multiport
backend = auto

[sshd]
enabled = true
filter = sshd
port = ssh
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600

[sshd-ddos]
enabled = true
filter = sshd-ddos
port = ssh
logpath = /var/log/auth.log
maxretry = 5
bantime = 7200

[webhook-auth]
enabled = true
filter = webhook-auth
port = 80,443
logpath = /var/log/nginx/access.log
maxretry = 5
bantime = 3600

# Custom filter for webhook authentication failures
[webhook-auth]
filter = \[error\] .* webhook authentication failed
port = http,https
logpath = /var/log/nginx/error.log
maxretry = 3
bantime = 3600
