apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["pods"]
    verbs: ["create", "update", "patch", "delete"]

  # Log configmaps and secrets at Metadata level
  - level: Metadata
    resources:
    - group: ""
      resources: ["secrets", "configmaps"]
    verbs: ["get", "create", "update", "patch", "delete"]

  # Log persistentvolumes changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["persistentvolumes"]
    verbs: ["create", "update", "patch", "delete"]

  # Log persistentvolumeclaim changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["persistentvolumeclaims"]
    verbs: ["create", "update", "patch", "delete"]

  # Log RBAC changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: "rbac.authorization.k8s.io"
      resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["create", "update", "patch", "delete"]

  # Log authentication and authorization at RequestResponse level
  - level: RequestResponse
    resources:
    - group: "authentication.k8s.io"
      resources: ["*"]
    verbs: ["create", "update", "patch", "delete"]
    
  - level: RequestResponse
    resources:
    - group: "authorization.k8s.io"
      resources: ["*"]
    verbs: ["create", "update", "patch", "delete"]

  # Log service account changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["serviceaccounts"]
    verbs: ["create", "update", "patch", "delete"]

  # Log node changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["nodes"]
    verbs: ["create", "update", "patch", "delete"]

  # Log failures at RequestResponse level
  - level: RequestResponse
    failedOnly: true

  # Log everything else at Metadata level
  - level: Metadata
    omitStages:
      - "RequestReceived"
