# Rsyslog configuration for enhanced security logging

# Provides support for local system logging
$ModLoad imuxsock

# Provides kernel logging support
$ModLoad imklog

# Set default permissions for all log files
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Rules
# Log all kernel messages to the console
kern.*                                                  /var/log/kern.log

# Log all authentication messages to auth.log
auth,authpriv.*                                         /var/log/auth.log

# Log all apt-related activities
if $programname == 'apt' or $programname == 'apt-get' or $programname == 'dpkg' then /var/log/apt/history.log
if $programname == 'apt' or $programname == 'apt-get' or $programname == 'dpkg' then stop

# Log cron activities
cron.*                                                  /var/log/cron.log

# Log user command history for sudo
if $programname == 'sudo' then /var/log/sudo.log
if $programname == 'sudo' then stop

# Log failed SSH authentication attempts separately
if $programname == 'sshd' and $msg contains 'Failed password' then /var/log/ssh-failures.log
if $programname == 'sshd' and $msg contains 'Invalid user' then /var/log/ssh-failures.log

# Log all webhook activities
if $programname == 'webhook' or ($programname == 'nginx' and $msg contains '/webhook') then /var/log/webhook.log

# Audit log forwarding
if $programname == 'audispd' or $programname == 'auditd' then /var/log/audit-forwarded.log

# Log everything else to syslog
*.*                                                     /var/log/syslog
