controller:
  image:
    registry: "localhost:32000"
    repository: "jenkins-devsecops"
    tag: "latest"
    pullPolicy: "Always"
  # Disable plugin installation since our custom image already contains plugins
  installPlugins: false
  ingress:
    enabled: true
    hostName: jenkins.local
    ingressClassName: public
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  servicePort: 8080
  jenkinsUrl: http://jenkins.local/
  # External access service configuration
  serviceType: ClusterIP
  nodePort: 30080
  podSecurityContext:
    fsGroup: 999  # docker group
    runAsUser: 1000
    runAsNonRoot: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 999  # docker group
    runAsNonRoot: false
    allowPrivilegeEscalation: true
  dnsConfig:
    nameservers:
      - "8.8.8.8"
  sidecars:
    configAutoReload:
      enabled: false
    dind:
      image: docker:24.0.5-dind
      name: docker-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      volumeMounts:
        - name: dind-graph-storage
          mountPath: /var/lib/docker
        - name: dind-sock
          mountPath: /var/run/docker.sock
  # Replace hostPath socket mount with DinD setup
  # Remove or ignore existing extraVolumes for socket
  extraVolumes:
    - name: dind-graph-storage
      emptyDir: {}
    - name: dind-sock
      emptyDir: {}
  extraVolumeMounts:
    - name: dind-sock
      mountPath: /var/run/docker.sock
    - name: dind-graph-storage
      mountPath: /var/lib/docker
persistence:
  storageClass: "microk8s-hostpath"
  size: "8Gi"
