controller:
  image:
    registry: "localhost:32000"
    repository: "jenkins-devsecops"
    tag: "latest"
    pullPolicy: "Always"
  
  # Disable plugin installation since our custom image already contains plugins
  installPlugins: false
  # Disable setup wizard since we're configuring everything via JCasC
  disableSetupWizard: true

  ingress:
    enabled: true
    hostName: jenkins.local
    ingressClassName: public
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  
  jenkinsUrl: http://jenkins.local/


sidecars:
  configAutoReload:
    enabled: false

persistence:
  storageClass: "microk8s-hostpath"
  size: "8Gi"

# Authentication and security configuration
serviceAccount:
  create: true

# Enable RBAC with cluster-admin permissions
rbac:
  create: true
  readSecrets: true

# Create ClusterRoleBinding for jenkins service account
clusterRoleBinding:
  create: true

# Agent configuration
agent:
  enabled: true

# Jenkins Configuration as Code
JCasC:
  defaultConfig: true
  overwriteConfiguration: true
  
  security:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: true
    apiToken:
      creationOfLegacyTokenEnabled: false
      tokenGenerationOnCreationEnabled: false
      usageStatisticsEnabled: true

  securityRealm: |-
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "${chart-admin-username}"
        name: "Jenkins Admin"
        password: "${chart-admin-password}"

  authorizationStrategy: |-
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

# Admin user configuration
admin:
  username: "admin"
  password: "admin123"
  createSecret: true
