controller:
  image:
    registry: "localhost:32000"
    repository: "jenkins-devsecops"
    tag: "latest"
    pullPolicy: "Always"
  installPlugins: false
 
  jenkinsUrlProtocol: "http"
  jenkinsUriPrefix: "/"
  ingress:
    enabled: true
    hostName: jenkins.local
    ingressClassName: public
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  servicePort: 8080
  jenkinsUrl: http://jenkins.local/
  serviceType: ClusterIP
  nodePort: 30080
  podSecurityContext:
    runAsUser: 0
    runAsNonRoot: false
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true
  dnsConfig:
    nameservers:
      - "8.8.8.8"
  sidecars:
    configAutoReload:
      enabled: false
  # Remove Docker-related volumes and mounts
persistence:
  storageClass: "microk8s-hostpath"
  size: "8Gi"

# Authentication and security configuration
serviceAccount:
  create: true
  annotations: {}

# Enable RBAC with cluster-admin permissions
rbac:
  create: true
  readSecrets: true

# Create ClusterRoleBinding for jenkins service account
clusterRoleBinding:
  create: true

# Agent configuration
agent:
  enabled: true
  defaultsProviderTemplate: ""