---
# Partial deployment playbook for Flask application only
- name: Deploy Flask Application Only
  hosts: localhost
  become: true
  vars_files:
    - ../vars/main.yml
  roles:
    - ../roles/prerequisites
    - ../roles/docker
    - ../roles/microk8s
    - ../roles/flask_app
