---
# Main playbook to orchestrate all setup steps for DevSecOps environment
- name: DevSecOps Environment Setup (MicroK8s Single Node)
  hosts: localhost
  become: false
  vars_files:
    - ../vars/main.yml
  roles:
    - role: ../roles/prerequisites
      tags: [prerequisites]
    - role: ../roles/docker
      tags: [docker]
    - role: ../roles/microk8s
      tags: [microk8s]
    - role: ../roles/jenkins_image
      tags: [jenkins_image, core_services]
    - role: ../roles/core_services
      tags: [core_services]
    - role: ../roles/monitoring_stack
      tags: [monitoring_stack, monitoring]
    - role: ../roles/flask_app
      tags: [flask_app, app]
    - role: ../roles/azure_access
      tags: [azure_access, azure]
    - role: ../roles/access_info
      tags: [access_info]
