---
# SIEM deployment playbook
- name: Deploy SIEM Security Monitoring
  hosts: localhost
  become: true
  vars_files:
    - ../vars/main.yml
  roles:
    - ../roles/prerequisites
    - ../roles/docker
    - ../roles/microk8s
    - ../roles/monitoring_stack
    - ../roles/siem_agents
