---
# SIEM role handlers
- name: restart auditd
  become: true
  systemd:
    name: auditd
    state: restarted

- name: restart fail2ban
  become: true
  systemd:
    name: fail2ban
    state: restarted

- name: restart rsyslog
  become: true
  systemd:
    name: rsyslog
    state: restarted

- name: reload auditd rules
  become: true
  command: auditctl -R /etc/audit/rules.d/siem.rules
  ignore_errors: yes

- name: check fail2ban status
  become: true
  command: fail2ban-client status
  register: fail2ban_status
  changed_when: false

- name: verify security services
  become: true
  systemd:
    name: "{{ item }}"
    state: started
  loop:
    - auditd
    - fail2ban
    - rsyslog
  changed_when: false
