ingress:
  enabled: true
  hosts:
    - name: sonarqube.local
      path: /
  ingressClassName: public
monitoringPasscode: "admin"
persistence:
  enabled: false

# Use external PostgreSQL
postgresql:
  enabled: false

jdbcOverwrite:
  enabled: true
  jdbcUrl: "jdbc:postgresql://postgresql.sonarqube.svc.cluster.local:5432/sonarqube"
  jdbcUsername: "sonarqube"
  jdbcPassword: "sonarpassword"

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

# Remove deprecated deployment strategy settings to suppress deprecation warnings
deployment:
  strategy: {}

# Set resource requests and limits to avoid resources warning
resources:
  requests:
    cpu: "500m"
    memory: "1024Mi"
  limits:
    cpu: "1000m"
    memory: "2048Mi"

# Unset edition and enable community edition
community:
  enabled: true
