---
- name: Update apt cache
  ansible.builtin.shell: |
    apt-get clean
    apt-get update
  become: true
  retries: 5
  delay: 15
  register: apt_update_result
  until: apt_update_result.rc == 0
  ignore_errors: false

- name: Ensure snapd is installed
  ansible.builtin.package:
    name: snapd
    state: present
  become: true
  retries: 3
  delay: 10

- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present
  become: true
  retries: 3
  delay: 10

- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present
  become: true
  retries: 3
  delay: 10

- name: Ensure python3-pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present
  become: true
  retries: 3
  delay: 10

- name: Ensure python3-venv is installed
  ansible.builtin.package:
    name: python3-venv
    state: present
  become: true
  retries: 3
  delay: 10
