---
# Ensure required tools are installed: snap, git, curl
- name: Ensure snapd is installed
  ansible.builtin.package:
    name: snapd
    state: present

- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present

- name: Ensure python3-pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Ensure python3-venv is installed
  ansible.builtin.package:
    name: python3-venv
    state: present
