apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver-service
  namespace: siem
spec:
  selector:
    app: webhook-receiver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
