apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-nginx-config
  namespace: siem
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        location /webhook {
            access_log /tmp/webhook-logs/webhook-access.log;
            error_log /tmp/webhook-logs/webhook-error.log;
            
            # Simple webhook logging
            if ($request_method = POST) {
                access_log /tmp/webhook-logs/webhook-payload.log;
            }
            
            return 200 '{"status":"received","timestamp":"now"}';
            add_header Content-Type application/json;
        }
        
        location /health {
            return 200 '{"status":"ok"}';
            add_header Content-Type application/json;
        }
    }
