---
# Cleanup playbook to remove deployed services
- name: DevSecOps Cleanup
  hosts: localhost
  become: false
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Cleanup Core Services
      ansible.builtin.shell: |
        microk8s helm3 uninstall jenkins -n jenkins || true
        microk8s helm3 uninstall sonarqube -n sonarqube || true
        microk8s helm3 uninstall postgresql -n sonarqube || true
        microk8s kubectl delete pvc -n sonarqube --all || true
        microk8s kubectl delete ns jenkins --ignore-not-found
        microk8s kubectl delete ns sonarqube --ignore-not-found
      when: "'core_services' in ansible_run_tags or ansible_run_tags == ['all']"
      tags: [core_services]
      
    - name: Cleanup Monitoring Stack
      ansible.builtin.shell: |
        microk8s helm3 uninstall loki -n monitoring || true
        microk8s helm3 uninstall grafana -n monitoring || true
        microk8s helm3 uninstall alloy -n monitoring || true
        microk8s kubectl delete ns monitoring --ignore-not-found
      when: "'monitoring' in ansible_run_tags or ansible_run_tags == ['all']"
      tags: [monitoring]
        
    - name: Cleanup Flask Application
      ansible.builtin.shell: |
        microk8s kubectl delete -f {{ inventory_dir }}/../k8s/ --ignore-not-found
        microk8s kubectl delete ns flask-app --ignore-not-found
      when: "'flask_app' in ansible_run_tags or ansible_run_tags == ['all']"
      tags: [flask_app]
        
    - name: Cleanup SIEM Stack
      ansible.builtin.shell: |
        microk8s kubectl delete deployment webhook-receiver -n monitoring || true
        microk8s kubectl delete service webhook-receiver-service -n monitoring || true
        microk8s kubectl delete ingress webhook-external -n monitoring || true
        docker rmi webhook-receiver:latest localhost:32000/webhook-receiver:latest || true
      when: "'siem' in ansible_run_tags or ansible_run_tags == ['all']"
      tags: [siem]
      
    - name: Remove Azure LoadBalancer services
      ansible.builtin.shell: |
        microk8s kubectl delete service jenkins-loadbalancer -n jenkins || true
        microk8s kubectl delete service sonarqube-loadbalancer -n sonarqube || true
        microk8s kubectl delete service grafana-loadbalancer -n monitoring || true
        microk8s kubectl delete service flask-app-loadbalancer -n flask-app || true
        microk8s kubectl delete service webhook-loadbalancer -n monitoring || true
      when: "'azure_access' in ansible_run_tags or ansible_run_tags == ['all']"
      tags: [azure_access]
        
    - name: Remove local Docker images
      ansible.builtin.shell: |
        docker rmi flask-k8s-app:latest localhost:32000/flask-k8s-app:latest || true
        docker rmi jenkins-devsecops:latest localhost:32000/jenkins-devsecops:latest || true
        docker rmi webhook-receiver:latest localhost:32000/webhook-receiver:latest || true
      when: "ansible_run_tags == ['all']"
      tags: [all]
        
    - name: Remove Helm repositories
      ansible.builtin.shell: |
        microk8s helm3 repo remove jenkins || true
        microk8s helm3 repo remove sonarqube || true
        microk8s helm3 repo remove grafana || true
        microk8s helm3 repo remove bitnami || true
      when: "ansible_run_tags == ['all']"
      tags: [all]

    - name: Display cleanup summary
      ansible.builtin.debug:
        msg: |
          🧹 Cleanup completed for tags: {{ ansible_run_tags | default(['all']) }}
          ✅ Selected components have been removed from the system.
