loki:
  auth_enabled: false
  
  server:
    http_listen_port: 3100
    
  common:
    path_prefix: /var/loki
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    replication_factor: 1
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory

  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    ingestion_rate_mb: 32
    ingestion_burst_size_mb: 64
    max_streams_per_user: 10000
    max_line_size: 0
    retention_period: 744h  # 31 days for security logs
    
  chunk_store_config:
    max_look_back_period: 744h

  table_manager:
    retention_deletes_enabled: true
    retention_period: 744h

  ruler:
    storage:
      type: local
      local:
        directory: /var/loki/rules
    rule_path: /var/loki/rules
    alertmanager_url: http://alertmanager:9093
    ring:
      kvstore:
        store: inmemory
    enable_api: true

# Security-focused configuration
monitoring:
  lokiCanary:
    enabled: true

persistence:
  enabled: true
  storageClassName: "microk8s-hostpath"
  size: "20Gi"  # Increased storage for security logs

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

serviceMonitor:
  enabled: false

ingress:
  enabled: false
