deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: "microk8s-hostpath"
    size: "10Gi"
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
