---
# Deploy Loki, Grafana, and Alloy using Helm with SIEM integration
- name: Create monitoring namespace
  ansible.builtin.shell: microk8s kubectl get ns monitoring || microk8s kubectl create ns monitoring
  args:
    executable: /bin/bash

- name: Add Grafana Helm repository if not present
  ansible.builtin.shell: |
    microk8s helm3 repo list | grep -q "grafana" || (microk8s helm3 repo add grafana https://grafana.github.io/helm-charts && microk8s helm3 repo update)
  args:
    executable: /bin/bash

- name: Deploy Loki via Helm
  ansible.builtin.shell: |
    microk8s helm3 status loki -n monitoring || microk8s helm3 install loki grafana/loki -n monitoring -f {{ playbook_dir }}/../../helm/loki/values.yaml
  args:
    executable: /bin/bash

- name: Create SIEM dashboard ConfigMaps with proper labels
  ansible.builtin.shell: |
    microk8s kubectl create configmap siem-overview-dashboard -n monitoring \
      --from-file=siem-overview.json={{ playbook_dir }}/../../monitoring/grafana/dashboards/siem-overview.json \
      --dry-run=client -o yaml | \
      microk8s kubectl label --local -f - grafana_dashboard=1 -o yaml | \
      microk8s kubectl apply -f -
    
    microk8s kubectl create configmap ssh-monitoring-dashboard -n monitoring \
      --from-file=ssh-monitoring.json={{ playbook_dir }}/../../monitoring/grafana/dashboards/ssh-monitoring.json \
      --dry-run=client -o yaml | \
      microk8s kubectl label --local -f - grafana_dashboard=1 -o yaml | \
      microk8s kubectl apply -f -
    
    # Add SIEM folder annotations
    microk8s kubectl annotate configmap siem-overview-dashboard -n monitoring grafana_folder="SIEM" --overwrite
    microk8s kubectl annotate configmap ssh-monitoring-dashboard -n monitoring grafana_folder="SIEM" --overwrite
  args:
    executable: /bin/bash

- name: Deploy Grafana with SIEM dashboards via Helm
  ansible.builtin.shell: |
    microk8s helm3 status grafana -n monitoring || microk8s helm3 install grafana grafana/grafana -n monitoring -f {{ playbook_dir }}/../../helm/grafana/values.yaml
  args:
    executable: /bin/bash

- name: Deploy Alloy with SIEM configuration via Helm
  ansible.builtin.shell: |
    microk8s helm3 status alloy -n monitoring || microk8s helm3 install alloy grafana/alloy -n monitoring -f {{ playbook_dir }}/../../helm/alloy/values.yaml
  args:
    executable: /bin/bash

- name: Wait for Loki StatefulSet
  ansible.builtin.shell: microk8s kubectl rollout status statefulset/loki -n monitoring --timeout=5m
  args:
    executable: /bin/bash

- name: Wait for Grafana Deployment
  ansible.builtin.shell: microk8s kubectl rollout status deployment/grafana -n monitoring --timeout=5m
  args:
    executable: /bin/bash

- name: Wait for Alloy DaemonSet
  ansible.builtin.shell: microk8s kubectl rollout status daemonset/alloy -n monitoring --timeout=5m
  args:
    executable: /bin/bash
